##############
#   Update   #
##############
# Whether or not to check for updates
# Default: true
checkUpdate: true
# Whether or not to download new updates
# Default: true
doUpdate: true
# Whether or not to report statistics to mcstats.org
# Default: true
enableMcstats: true
